# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 07:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import interview.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('mobile_phone', models.CharField(default='', max_length=14)),
                ('address', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('qualification', models.CharField(default='', max_length=50)),
                ('institute', models.CharField(default='', max_length=50)),
                ('experienced', models.CharField(help_text='e.g Fresh, 11 Months, 2 Years and 11 Months', max_length=10)),
                ('cv', models.FileField(help_text='Why cv required? Becuase while taking interview, interviewer mostly want to look candidate cv', upload_to=interview.models.cv_directory_path)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview_scheduled', 'Interview Scheduled'), ('interview_declined', 'Interview Declined'), ('not_recommended', 'Not Recommended after Interview'), ('recommended', 'Recommended after Interview'), ('job_offered', 'Job Offered'), ('job_accepted', 'Job Accepted'), ('job_declined', 'Job Declined'), ('joined', 'Joined')], default='applied', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Interview Scheduled'), ('cancelled', 'Cancelled'), ('noshow', 'No Show'), ('recommended', 'Recommended'), ('not_recommended', 'Not Recommended'), ('second_interview', 'Recommended Second Interview')], default='scheduled', max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Candidate')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewRemarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('oop_concepts', models.IntegerField(default=0, help_text='in percentage, by default set to 0 %')),
                ('db_concepts', models.IntegerField(default=0, help_text='in percentage, by default set to 0 %')),
                ('ds_concepts', models.IntegerField(default=0, help_text='in percentage, by default set to 0 %')),
                ('recursion_concepts', models.IntegerField(default=0, help_text='in percentage, by default set to 0 %')),
                ('remarks', models.TextField()),
                ('overall_score', models.IntegerField(help_text='Out of 10')),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='interview.Interview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
