# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewremarks',
            name='remarks_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experienced',
            field=models.CharField(blank=True, help_text='e.g Fresh, 11 Months, 2 Years and 11 Months', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='institute',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewremarks',
            name='db_concepts',
            field=models.IntegerField(blank=True, default=0, help_text='in percentage, by default set to 0 %', verbose_name='Database Concepts'),
        ),
        migrations.AlterField(
            model_name='interviewremarks',
            name='ds_concepts',
            field=models.IntegerField(blank=True, default=0, help_text='in percentage, by default set to 0 %', verbose_name='Data Structure Concepts'),
        ),
        migrations.AlterField(
            model_name='interviewremarks',
            name='oop_concepts',
            field=models.IntegerField(blank=True, default=0, help_text='in percentage, by default set to 0 %', verbose_name='OOP Concepts'),
        ),
        migrations.AlterField(
            model_name='interviewremarks',
            name='recursion_concepts',
            field=models.IntegerField(blank=True, default=0, help_text='in percentage, by default set to 0 %', verbose_name='Recursion Concepts'),
        ),
    ]
